# Generated by Django 4.2.17 on 2025-01-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_userprofile_achievements"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="photo",
        ),
    ]
